package:com.swfp.factory
package:com.mediatek.gba
package:com.mediatek.ims
package:com.android.cts.priv.ctsshim
package:com.google.android.youtube
package:org.simalliance.openmobileapi.uicc2terminal
package:com.transsion.statisticalsales
package:com.hilauncherconfig
package:com.android.internal.display.cutout.emulation.corner
package:com.google.android.ext.services
package:com.android.internal.display.cutout.emulation.double
package:com.android.providers.telephony
package:com.transsion.plat.appupdate
package:com.google.android.googlequicksearchbox
package:com.android.providers.calendar
package:com.android.providers.media
package:com.google.android.onetimeinitializer
package:com.google.android.ext.shared
package:com.transsion.screenshot
package:com.mediatek.location.lppe.main
package:com.android.wallpapercropper
package:com.transsion.magicfont
package:com.mediatek.schpwronoff
package:org.simalliance.openmobileapi.service
package:com.transsion.agingfunction
package:com.android.documentsui
package:android.auto_generated_rro__
package:com.android.externalstorage
package:com.mediatek.ygps
package:com.mediatek.simprocessor
package:com.android.htmlviewer
package:com.android.companiondevicemanager
package:com.android.mms.service
package:com.android.providers.downloads
package:com.google.android.apps.messaging
package:com.mediatek.engineermode
package:com.westalgo.factorycamera
package:com.transsion.magazineservice
package:com.mediatek.omacp
package:com.google.android.configupdater
package:com.mediatek.wfo.impl
package:com.android.defcontainer
package:com.android.providers.downloads.ui
package:com.clover.secscanner
package:com.android.vending
package:com.android.pacprocessor
package:com.android.simappdialog
package:com.android.internal.display.cutout.emulation.tall
package:com.android.certinstaller
package:com.transsion.theme.icon
package:com.android.carrierconfig
package:android
package:com.android.contacts
package:com.mediatek.emcamera
package:com.superscreenshot
package:com.transsion.powercenter
package:com.aimatch.cleaner
package:com.android.egg
package:com.android.mtp
package:com.android.stk
package:com.android.backupconfirm
package:com.mediatek.security
package:com.jupiter.tornado
package:com.transsion.readmode
package:com.android.statementservice
package:com.google.android.gm
package:com.google.android.apps.tachyon
package:com.mediatek.mdmlsample
package:com.transsion.camera
package:com.transsion.datatransfer
package:com.android.settings.intelligence
package:com.mediatek.providers.drm
package:com.transsion.weathers
package:com.android.systemui.theme.dark
package:com.transsion.faceid
package:com.google.android.setupwizard
package:com.android.providers.settings
package:com.transsion.ivoice
package:com.android.sharedstoragebackup
package:com.mediatek.batterywarning
package:com.facebook.services
package:com.android.printspooler
package:org.simalliance.openmobileapi.uicc1terminal
package:com.gallery20
package:com.transsion.policycenter
package:com.westalgo.aftersalecamera
package:com.android.incallui
package:com.transsion.phonemanager
package:com.android.se
package:com.android.inputdevices
package:com.google.android.apps.wellbeing
package:com.android.bips
package:com.mediatek
package:com.example
package:com.google.android.apps.docs
package:com.google.android.apps.maps
package:com.transsion.filemanagerx
package:com.hoffnung
package:com.android.cellbroadcastreceiver
package:com.google.android.webview
package:com.mediatek.nlpservice
package:com.android.server.telecom
package:com.google.android.syncadapters.contacts
package:com.android.keychain
package:com.android.gallery3d
package:com.google.android.packageinstaller
package:com.transsion.applock
package:com.google.android.gms
package:com.google.android.gsf
package:com.google.android.ims
package:com.google.android.tts
package:com.android.calllogbackup
package:com.google.android.partnersetup
package:com.transsion.fmradio
package:com.mediatek.atmwifimeta
package:com.transsion.batterylab
package:com.transsion.screenrecord
package:com.transsion
package:com.android.proxyhandler
package:com.android.inputmethod.latin
package:com.transsion.phoenix
package:com.reallytek.wg
package:com.google.android.feedback
package:com.google.android.printservice.recommendation
package:com.google.android.calendar
package:com.android.managedprovisioning
package:com.mediatek.calendarimporter
package:com.transsion.aibox
package:com.mediatek.thermalmanager
package:com.mediatek.callrecorder
package:com.android.providers.partnerbookmarks
package:com.android.smspush
package:com.android.wallpaper.livepicker
package:com.transsion.overlaysuw
package:com.mediatek.gnssdebugreport
package:com.transsion.videocallenhancer
package:com.facebook.system
package:com.google.android.gms.policy_sidecar_aps
package:com.transsion.smartpanel
package:com.google.android.backuptransport
package:com.transsion.microintelligence
package:com.android.storagemanager
package:com.android.bookmarkprovider
package:com.android.settings
package:com.rlk.mi
package:com.mediatek.mdmconfig
package:com.transsion.splitscreen
package:android.autoinstalls.config.transsion.device
package:com.mediatek.lbs.em2.ui
package:com.android.cts.ctsshim
package:com.sh.smart.caller
package:com.android.vpndialogs
package:com.transsion.keyguardgesture
package:com.android.phone
package:com.android.shell
package:com.transsion.systemupdate
package:com.android.wallpaperbackup
package:com.android.providers.blockednumber
package:com.transsion.soundrecorder
package:com.android.providers.userdictionary
package:com.android.emergency
package:com.transsion.hilauncher
package:com.android.location.fused
package:com.android.systemui
package:com.transsion.calculator
package:com.android.bluetoothmidiservice
package:com.transsion.os.typeface
package:com.mediatek.location.mtknlp
package:com.facebook.appmanager
package:com.android.traceur
package:com.mediatek.mtklogger
package:com.transsion.notebook
package:com.android.bluetooth
package:com.android.wallpaperpicker
package:com.android.providers.contacts
package:com.transsion.chromecustomization
package:com.android.captiveportallogin
package:com.transsion.deskclock
package:com.google.android.apps.restore